version: "3"

services:
  indexer: 
    image: hydra-indexer:v3-latest
    environment:
      - DB_NAME=indexer-db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - NEW_BLOCK_TIMEOUT_SEC=150000
      - WS_PROVIDER_ENDPOINT_URI=ws://substrate:9944/
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
    depends_on:
      - substrate
      - redis
      - db

  substrate:
    image: paritytech/substrate-playground-template-node-template:sha-7212614
    ports:
      - "9944"
    command: ["./target/release/node-template", "--dev", "--tmp", "--ws-external"]
  
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379"

  db:
    image: postgres:12
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
